### ISSUE TITLE
Let clap do the parsing for you

### ISSUE THREAD

**Issue by irevoire** [NoodleSamaChan/snake#2]
Hello,

In your CLI, instead of getting strings everywhere and then doing complex matches in the code like here:
https://github.com/NoodleSamaChan/snake/blob/7cb4ad0d4606562310bf9955ee126cf49f7923a7/src/main.rs#L118-L121

## Easy

You should update your CLI here to use a boolean here:
https://github.com/NoodleSamaChan/snake/blob/7cb4ad0d4606562310bf9955ee126cf49f7923a7/src/main.rs#L27-L28

That’s called a « flag » in clap, you can find the documentation [here](https://docs.rs/clap/latest/clap/_derive/index.html#arg-types).
And it’ll then be `false` by default and can be set to `true` by using the `--bad-berries` argument (without any value)

## Medium

Same thing for this other argument:
https://github.com/NoodleSamaChan/snake/blob/7cb4ad0d4606562310bf9955ee126cf49f7923a7/src/main.rs#L25-L26

Let `clap` parse the string for you and use an enum instead of a string:
```rust
#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, ValueEnum)]
enum Difficulty {
    Easy,
    Medium,
    Hard,
}
```

See https://docs.rs/clap/latest/clap/_derive/_tutorial/chapter_3/index.html#enumerated-values for more informations

**Comment by NoodleSamaChan** [comment]
hello

solved by this ef2c568

thanks !
