### ISSUE TITLE
A lot of function updates both the `World` and the `WindowBuffer`

### ISSUE THREAD

**Issue by irevoire** [NoodleSamaChan/snake#3]
Hey,

You have a lot of functions that update both the `World` and the `WindowBuffer`; ideally, that shouldn’t happen.
Here is an example:

https://github.com/NoodleSamaChan/snake/blob/7cb4ad0d4606562310bf9955ee126cf49f7923a7/src/main.rs#L490

Or the update function that should update only the `World` and take a read-only reference to the window buffer:

https://github.com/NoodleSamaChan/snake/blob/7cb4ad0d4606562310bf9955ee126cf49f7923a7/src/main.rs#L97-L102

Or the handle user input:
https://github.com/NoodleSamaChan/snake/blob/7cb4ad0d4606562310bf9955ee126cf49f7923a7/src/main.rs#L172-L177

**Comment by NoodleSamaChan** [comment]
thanks for the feedback

fixed here 17b02c8

Cheers
