### ISSUE TITLE
`handle_user_input` shouldn’t update the position of the snake

### ISSUE THREAD

**Issue by irevoire** [NoodleSamaChan/snake#4]
Handle user input should **only** extract arguments from the mouse, keyboard, and stuff like that but never modify the snake or, even worse, the `WindowBuffer`.
https://github.com/NoodleSamaChan/snake/blob/7cb4ad0d4606562310bf9955ee126cf49f7923a7/src/main.rs#L203-L221

This could be the cause of your bug. You update the snakito once while getting the user input and then a second time while `updat`ing the world (this time, it’s legitimate).

**Comment by NoodleSamaChan** [comment]
thanks !

fixed in 90dd41b

:)
